language: csharp
solution: C#/CustomerProject.sln
branches:
  only:
  - master
  - development
notifications:
  email: false
  dotnet: 2.0.0
dist: trusty
install:
- dotnet restore
script:
- dotnet build